 /*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Currency;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Date;
import java.util.Scanner;

public class App {

    private static String filepath = "src/main/java/Currency/RateTxt.txt";;

    public static void main(String[] args)
    {
        // TODO: open the in-memory file containing ER and and pass it into constructor of CC


        CurrencyConverter cc = new CurrencyConverter(filepath);
        Admin admin = new Admin(cc);
        User user = new User(cc);

        Scanner inputScanner = new Scanner(System.in);
        String userType = null;
        while (true) {
            System.out.println("Are you an Admin or User? [admin/user]");
            userType = inputScanner.nextLine();
            if (userType.equals("admin")) {
                break;
            } else if (userType.equals("user")) {
                break;
            } else {
                System.out.println("Please enter a valid input.");
            }
        }
        while (true){
            System.out.println("Please enter a command:");
            String command = inputScanner.nextLine();
            switch(userType){
                case("admin"):
                    if (command.equals("display")){
                        admin.displayCurrencies();
                    }
                    if (command.equals("add ex")) {
                        System.out.println("Please input CurrencyA-CurrencyB-Rate-Date [dd/mm/yyyy]");
                        String userInput = inputScanner.nextLine();
                        String formattedString[] = userInput.split("-");
                        if (formattedString.length != 4) {
                            System.out.println("The input format is incorrect.\nPlease try again.");
                        }
                        else {
                            try {
                                admin.addNewRate(formattedString[0].toUpperCase(), formattedString[1].toUpperCase(), Double.parseDouble(formattedString[2]),
                                        new SimpleDateFormat("dd/MM/yyyy").parse(formattedString[3]));
                            } catch (ParseException | NumberFormatException e) {
                                System.out.println("The input format is incorrect.\nPlease try again.");
                                e.printStackTrace();
                            }
                        }
                    }
                    if (command.equals("find")){
                        System.out.println("Please input CurrencyA-CurrencyB");
                        String userInput = inputScanner.nextLine();
                        String formattedString[] = userInput.split("-");
                        cc.getAllRate(formattedString[0].toUpperCase(),formattedString[1].toUpperCase());
                    }
                    if (command.equals("add currency")){
                        System.out.println("Please input name of currency");
                        String currencyName = inputScanner.nextLine();
                        System.out.println("Please input a date [dd/mm/yyyy]");
                        try{
                            Date date = new SimpleDateFormat("dd/MM/yyyy").parse(inputScanner.nextLine());
                            admin.addCurrency(currencyName, date);
                        } catch (ParseException e) {
                            System.out.println("Incorrect format of date entered.");
                            e.printStackTrace();
                        }
                    }
                case("user"):
                    if (command.equals("convert")){
                        double amount = user.exchangeCurrency("USD","CNY",10);
                        System.out.printf("10 USD is converted to %.2fCNY.\n",amount);
                    }
            }
        }
    }
}
